[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; Serial monitor baud rate
monitor_speed = 115200

; Libraries — PlatformIO downloads these automatically
lib_deps =
    mikalhart/TinyGPSPlus
    bblanchon/ArduinoJson

; Upload speed (increase if flashing is slow)
upload_speed = 921600

upload_port = COM3
